project_name: "deepfake_detection"

# data
data:
 dataset: "faceforensics++"
 raw_dir: "data/raw/faceforensics++"
 img_size: 256
 num_workers: 4
 train_fraction: 0.4 # rapid prototyping

model:
 backbone: "xception"
 pretrained: true
 embedding_dim: 128

train:
 batch_size_base: 32
 batch_size_novel: 8
 epochs: 10
 warmup_epochs: 3
 learning_rate: 0.0001