project_name: "deepfake_detection"

data:
 dataset: "faceforensics++"
 raw_dir: "data/raw/faceforensics++"
 img_size: 256
 num_workers: 4

model:
 backbone: "efficientnet_b0"
 pretrained: true
 embedding_dim: 128

train:
 batch_size_base: 64
 batch_size_novel: 16
 epochs: 30
 learning_rate: 0.001