project_name: "deepfake_detection_xception"

data:
 dataset: "faceforensics++"
 raw_dir: "data/raw/faceforensics++"
 img_size: 256
 num_workers: 4
 train_fraction: 0.4

model:
 backbone: "xception"            
 pretrained: true
 embedding_dim: 128

train:
 batch_size_base: 32     
 batch_size_novel: 8
 epochs: 30
 warmup_epochs: 1
 learning_rate: 0.0001